version: "2"
plugins:
  phpcodesniffer:
    enabled: true
    config:
      standard: "WordPress"
      ignore_warnings: true
    checks:
      Squiz Commenting InlineComment InvalidEndChar:
        enabled: false
      Squiz Commenting InlineComment SpacingBefore:
        enabled: false
exclude_patterns:
- "tests/"
- "bin/"
- "vendor/"
